### ISSUE TITLE
METAR

### ISSUE THREAD

**Issue by hannahmsolomon** [Flight-Path-Analysis/FlightPathAnalysis#115]
Figure out how to decode METAR data in python.

Possible packages include metar and metpy (specifically parse_metat_to_dataframe)

**Comment by Andrerg01** [comment]
@hannahmsolomon Provided with notebook with full breakdown of METAR variables on commit c5166ed8e517f0b2035a177c51245870ce5f5268.
Need to implement that into data interpretation step.

**Comment by hannahmsolomon** [comment]
Note: NaN means that there is no entry because that weather feature had no impact, rather than it not being reported.

**Comment by Andrerg01** [comment]
Closed and implemented
