### ISSUE TITLE
Which routes do we want to use?

### ISSUE THREAD

**Issue by hannahmsolomon** [Flight-Path-Analysis/FlightPathAnalysis#116]
We have decided we want to look at two months: January 2023 for cold weather and a summer month for hot weather.

We want either 2 or 3 routes.  For the long route, we are looking at JFK to LAX.  Hannah will create a poll to decide on a short/medium route.

**Comment by hannahmsolomon** [comment]
Pulling info on popular flights from the following sites:
https://www.airfarewatchdog.com/blog/44259160/these-are-the-10-busiest-air-routes-in-the-u-s/
https://www.directflights.com/most-popular-routes-us
https://simpleflying.com/united-states-top-15-routes/
https://simpleflying.com/what-are-the-usas-busiest-domestic-air-routes/#atlanta---fort-lauderdale-254-396-seats

**Comment by hannahmsolomon** [comment]
Poll: https://PollEv.com/surveys/Thdo1j91Pvebs2QOXyc6j/respond

**Comment by Andrerg01** [comment]
Putting it here for the record: 
Decision was made to analyze AT LEAST two routes (one long and one short) in AT LEAST two different seasons (Jan and Jul)

**Comment by hannahmsolomon** [comment]
We have decided to add 2 more routes.  For the short route, we chose LAX to SFO (about 1h 25m flight).  For the medium route, we chose DEN to SEA (about 3h 5m flight).
